version: '3.8'

services:
  devsecopsapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devsecopsapp
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./init-db.sql:/app/init-db.sql
    networks:
      - devsecops-network

networks:
  devsecops-network:
    driver: bridge
